### ISSUE TITLE
Move config files into an untracked directory

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-baseline-builder#13]
There are a couple personalized config files that are inside the main directory, so git wants to track changes to them, but it would be bad if someone pushed up their own config file (since it has a password).  Maybe the best option would be to add an example directory which contains dummy versions and try to pull the config from another folder?

Alternatively, allow the config file for hypervisor to be passed in as an argument, so the file could be stored outside the repo folder structure entirely, making supporting multiple hypervisors easier.

**Comment by jmartin-r7** [comment]
Would marking these files in the `.gitingnore` file solve this? We could provide a default and enforce that a user can only add specifically when changes are needed to the default.

This would be similar to how `exsi_config.json` is handled.

**Comment by bwatters-r7** [comment]
I'm referring to esxi_config.  Since the filename is hard-coded, any time you want to run baseline builder on another system, you have to toggle the filenames of your configs.  That's already kind of a pain, to be honest, but if you want to store two (or more) config files, then you have to toggle names and add the possible names to .gitignore if you want them side-by-side to make renaming easier.  

Not sure how normal it is, but it seems like adding an "examples" folder with the base configs in it and a 'configs' folder with nothing in it tracked would be a solution.

**Comment by bwatters-r7** [comment]
I already have a branch that I;m testing that supports prepended vm names and a command-line config file option.

**Comment by jmartin-r7** [comment]
Adding as a command line option to override the default works for me `-c PATH_TO_FILE || --config=PATH_TO_FILE`? I used a default really just for my initial use case and made sure to put as an ignored file.

Post the PR and tag both issues, I will review and make adjustments as needed.

**Comment by jmartin-r7** [comment]
Fixed by #15
