### ISSUE TITLE
Python installed correctly on some machines

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-baseline-builder#24]
Windows 7 and Windows 2K8 machines no longer appear to get python installed into the C:\tools directory.
Currently on Windows 7x64 sp1:
![image](https://user-images.githubusercontent.com/17987018/39523016-d22519ec-4dd9-11e8-9a55-61bf420602bc.png)
Windows 10x64_1709
![image](https://user-images.githubusercontent.com/17987018/39523079-09096a3a-4dda-11e8-9fa4-59f6bab776be.png)

**Comment by bwatters-r7** [comment]
The install looks right in the logs...
```

**Comment by bwatters-r7** [comment]
This could be an issue where python 3 installs and removes python 2...  Not sure.  Will dig more.

**Comment by jmartin-r7** [comment]
Fixed by #26
